#!/usr/bin/env python

class SchematicDraw:
	_capstyle  = ["none","square","round"]
	_dashstyle = ["solid","dotted","dashed","center","phantom"]
	_filltype  = ["hollow","fill","mesh","hatch","void"]

	def add_version():
		_version = "20110115"
		return "v " + _version + " 2\n"
	
	def add_to( string ):
		return " " + str(string)

	def box(x, y, w, h, c, linewidth, capstyle, dashstyle, dashlength, filltype, fillwidth, argle1, pitch1, angle2, pitch2):
		sout = "B" + add_to(x) + add_to(y) + add_to(w) + " "
		sout = sout + add_to(h)+ add_to(c) + add_to(linewidth) + " "
		sout = sout + add_to(capstyle) + " "

		# if dashstyle is not used for SOLID and DOTTED
		if dashstyle == 0 or dashstyle == 1:
			dashlenght = -1
			if dashstyle == 0:
				dashspace  = -1
		sout = sout + add_to(dashstyle) + add_to(dashlength) + " "
		sout = sout + add_to(dashspace) + add_to(filltype) + " "
		
		if filltype == 0:
			fillwidth = -1
			angle1 = -1
			angle2 = -1
			pitch1 = -1
			pitch2 = -1
		
		sout = sout + add_to(fillwidth) + add_to(angle1) + " "
		sout = sout + add_to(pitch1) + add_to(angle2) + " "
		sout = sout + add_to(pitch2) 

		return sout
		

if __name__ == "__main__":
	print "This is an test, of how to create a gschem symbol"

	print "done"

# Notes:
# Pins should all be 300 mils long.
# and 400 mils between vertically pins.

